Early setup ci/cd

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -2,22 +2,21 @@ name: Integration Workflow
 
 on:
   push:
-    branches: ["main"]
+    branches: ['main']
   pull_request:
-    branches: ["main"]
+    branches: ['main']
 
 jobs:
   build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        node-version: [18.x, 20.x]
-
+        node-version: [18]
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
-      - name: Use Node.js ${{ matrix.node-version }}
+      - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
@@ -25,8 +24,72 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      # - name: Check for linting issues
-      #   run: npm lint
+      # - name: Run lint
+      #   run: npm run lint
+      #   continue-on-error: false
 
-      - name: Build
-        run: npm run build
+  deploy:
+    runs-on: ubuntu-latest
+    needs: [build]
+    steps:
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: 18
+
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up SSH connection
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.SERVER_IP }}
+          username: ${{ secrets.USER_NAME }}
+          key: ${{ secrets.SEVER_SSH_KEY }}
+          port: ${{ secrets.PORT }}
+          script: |
+            set -e
+
+            export NVM_DIR="$HOME/.nvm"
+            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
+            nvm install 18
+            nvm use 18
+
+            echo "Changing directory to /www/wwwroot/clients/dataAction"
+            if ! cd /www/wwwroot/clients/dataAction; then
+              echo "Failed to change directory as required by me"
+              exit 1
+            fi
+            echo "Reseting Local Changes"
+              if ! git reset --hard; then
+                  echo "Failed to reset local changes"
+                  exit 1;
+              fi
+            echo "Pulling latest code from origin/main"
+            if ! git pull origin main; then
+              echo "Failed to pull latest code"
+              exit 1
+            fi
+            # echo "Removing every built files and cache"
+            # if ! npm run cleanup; then
+            #     echo "Couldn't run cleanups"
+            #     exit 1
+            # fi
+            echo "Installing dependencies"
+            if ! npm install; then
+              echo "Couldn't install packages"
+              exit 1
+            fi
+            echo "Building for production "
+            if ! npm run build; then
+              echo "Couldn't rebuild"
+              exit 1
+            fi
+            echo "Start Production server with pm2"
+            if ! npm run deploy; then
+              echo "Couldn't Start production with pm2"
+              exit 1
+            fi
+            echo "Deployment successful"
+
+
